# Generated by Django 5.1.4 on 2025-03-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('program', models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('bba', 'BBA'), ('mba', 'MBA'), ('bca', 'BCA'), ('mca', 'MCA'), ('bpharm', 'B.Pharm'), ('mpharm', 'M.Pharm')], max_length=10)),
                ('specialization', models.CharField(max_length=100)),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(upload_to='uploads/photos/')),
                ('signature', models.ImageField(upload_to='uploads/signatures/')),
                ('tenth_marksheet', models.FileField(upload_to='uploads/marksheets/')),
                ('twelfth_marksheet', models.FileField(upload_to='uploads/marksheets/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('program_of_interest', models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('bba', 'BBA'), ('mba', 'MBA'), ('bsc', 'B.Sc'), ('phd', 'Ph.D')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        
    ]
