# Generated by Django 5.1.4 on 2025-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('inquiry_type', models.CharField(choices=[('admission', 'Admission Inquiry'), ('program', 'Program Information'), ('campus', 'Campus Facilities'), ('scholarship', 'Scholarships & Financial Aid'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('Engineering', 'engineering'), ('Sciences', 'sciences'), ('Management', 'management')], max_length=100)),
                ('extra', models.CharField(max_length=90)),
            ],
        ),
    ]
