# Generated by Django 5.1.4 on 2025-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactmessage_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='extra',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, unique=True),
        ),
    ]
