# Generated by Django 5.1.4 on 2025-03-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.CharField(default='unknown', max_length=100, unique=True)),
            ],
        ),
    ]
