# Generated by Django 5.1.4 on 2025-03-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
